#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

post-deploy-script() {
    local APP="$1"; verify_app_name "$APP"
    local SCRIPT_PATH="$DOKKU_ROOT/$APP/POST_DEPLOY_SCRIPT"

    dokku_log_info1 "Connecting to web network"
    local containers="$(get_app_running_container_ids $APP)"
    dokku_log_info1 "$containers"
    for container_id in $(get_app_running_container_ids $APP)
    do
        dokku_log_info1 "connecting $container_id to web"
        docker network connect web $container_id
    done
    
    dokku_log_info1 "Connecting to web network done..."
}

post-deploy-script "$@"
